INSERT INTO cursos (cod_cur, nom_cur, dat_inc, estado, sit) VALUES (1, 'ANÁLISE E DESENVOLVIMENTO DE SISTEMAS', '1974-08-21', '1', 'Ativo');
INSERT INTO cursos (cod_cur, nom_cur, dat_inc, estado, sit) VALUES (2, 'SECRETARIADO E ASSESSORIA INTERNACIONAL', '1991-09-30', '1', 'Ativo');
INSERT INTO cursos (cod_cur, nom_cur, dat_inc, estado, sit) VALUES (3, 'EDIFÍCIOS', '1973-04-10', '1', 'Ativo');
INSERT INTO cursos (cod_cur, nom_cur, dat_inc, estado, sit) VALUES (4, 'ELETRÔNICA INDUSTRIAL', '1991-01-01', '1', 'Ativo');
INSERT INTO cursos (cod_cur, nom_cur, dat_inc, estado, sit) VALUES (5, 'GESTÃO DE TURISMO', '2008-01-01', '1', 'Ativo');
INSERT INTO cursos (cod_cur, nom_cur, dat_inc, estado, sit) VALUES (6, 'HIDRÁULICA E SANEAMENTO AMBIENTAL', '2012-09-17', '1', 'Ativo');
INSERT INTO cursos (cod_cur, nom_cur, dat_inc, estado, sit) VALUES (7, 'INSTALAÇÕES ELÉTRICAS', '2024-07-01', '1', 'Ativo');
INSERT INTO cursos (cod_cur, nom_cur, dat_inc, estado, sit) VALUES (8, 'GESTÃO EMPRESARIAL', '2024-07-01', '1', 'Ativo');
INSERT INTO cursos (cod_cur, nom_cur, dat_inc, estado, sit) VALUES (9, 'MATERIAIS', '1973-04-10', '1', 'Ativo');
INSERT INTO cursos (cod_cur, nom_cur, dat_inc, estado, sit) VALUES (10, 'MECÂNICA DE PRECISÃO', '1973-04-10', '1', 'Ativo');
INSERT INTO cursos (cod_cur, nom_cur, dat_inc, estado, sit) VALUES (11, 'MICROELETRÔNICA', '1994-01-01', '1', 'Ativo');
INSERT INTO cursos (cod_cur, nom_cur, dat_inc, estado, sit) VALUES (12, 'TECNOLOGIA EM ESTRADAS', '1973-04-10', '1', 'Ativo');
INSERT INTO cursos (cod_cur, nom_cur, dat_inc, estado, sit) VALUES (13, 'PROCESSOS DE PRODUÇÃO', '1973-04-10', '1', 'Ativo');
INSERT INTO cursos (cod_cur, nom_cur, dat_inc, estado, sit) VALUES (14, ' PROJETOS', '1973-04-10', '1', 'Ativo');
INSERT INTO cursos (cod_cur, nom_cur, dat_inc, estado, sit) VALUES (15, 'SOLDAGEM', '1988-04-11', '1', 'Ativo');
INSERT INTO cursos (cod_cur, nom_cur, dat_inc, estado, sit) VALUES (16, 'GESTAO DE EMPREENDIMENTOS GASTRONOMICOS', '2025-01-01', '1', 'Ativo');
INSERT INTO cursos (cod_cur, nom_cur, dat_inc, estado, sit) VALUES (17, 'PRODUCAO CULTURAL', '2024-01-01', '1', 'Ativo');
INSERT INTO cursos (cod_cur, nom_cur, dat_inc, estado, sit) VALUES (18, 'PAISAGISMO E JARDINAGEM', '2024-01-01', '1', 'Ativo');
INSERT INTO cursos (cod_cur, nom_cur, dat_inc, estado, sit) VALUES (19, 'GESTAO DA QUALIDADE', '2021-01-01', '1', 'Ativo');
INSERT INTO cursos (cod_cur, nom_cur, dat_inc, estado, sit) VALUES (20, 'FABRICAÇÃO MECÂNICA', '2025-07-01', '1', 'Inativo');
INSERT INTO cursos (cod_cur, nom_cur, dat_inc, estado, sit) VALUES (21, 'GESTÃO DA PRODUÇÃO INDUSTRIAL', '2025-07-01', '1', 'Inativo');
INSERT INTO cursos (cod_cur, nom_cur, dat_inc, estado, sit) VALUES (22, 'PROJETOS MECÂNICOS', '2025-07-01', '1', 'Inativo');
INSERT INTO cursos (cod_cur, nom_cur, dat_inc, estado, sit) VALUES (23, 'REFRIGERAÇÃO E CLIMATIZAÇÃO', '2025-01-01', '1', 'Inativo');